### ISSUE TITLE
cmake & make error in deform

### ISSUE THREAD

**Issue by JuheonYi** [HiKapok/DAN#1]
Hi, thanks for sharing the code.

I tried to train the models with the codes provided, but encountered an error when building the "deform" library.

When I type cmake .. and make in deform/build directory, I encounter with the following error message. Could you give me some advice an how to solve the error, or what CUDA version and GPU you are using?
(I am using GTX 1080 Ti and CUDA 9.0, by the way).

Would really appreciate if you could give me some help!

1 error detected in the compilation of "/home/johnyi/Documents/DAN-master/cpp/Deform/build/deform_psroi_pooling_op_gpu.cpp1.ii".
CMake Error at cuda_compile_2_generated_deform_psroi_pooling_op_gpu.cu.o.cmake:280 (message):
  Error generating file
  /home/johnyi/Documents/DAN-master/cpp/Deform/build/CMakeFiles/cuda_compile_2.dir//./cuda_compile_2_generated_deform_psroi_pooling_op_gpu.cu.o

CMakeFiles/deform.dir/build.make:70: recipe for target 'CMakeFiles/cuda_compile_2.dir/cuda_compile_2_generated_deform_psroi_pooling_op_gpu.cu.o' failed
make[2]: *** [CMakeFiles/cuda_compile_2.dir/cuda_compile_2_generated_deform_psroi_pooling_op_gpu.cu.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/deform.dir/all' failed

**Comment by destiny311** [comment]
请问你解决问题了吗？我也遇到了cmake编译的问题。-- Found CWD: /home/ChenGb/wl/renlianshibie/jiance/PyramidBox-master/datasets/DAN-master/cpp/ExtraLib/build
-- Found GPU_CAPABILITY: gencode arch=compute_61,code=sm_61

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tensorflow'
-- Found TF_INC: 
-- Found TF_INC_EXTERNAL: /external/nsync/public
-- Found TF_LIB: 
-- Configuring done
-- Generating done
但是我是装了tensorflow的啊

**Comment by HiKapok** [comment]
@JuheonYi 看看虚拟环境有没有问题

**Comment by Svijay98** [comment]
> Hi, thanks for sharing the code.
> 
> I tried to train the models with the codes provided, but encountered an error when building the "deform" library.
> 
> When I type cmake .. and make in deform/build directory, I encounter with the following error message. Could you give me some advice an how to solve the error, or what CUDA version and GPU you are using?
> (I am using GTX 1080 Ti and CUDA 9.0, by the way).
> 
> Would really appreciate if you could give me some help!
> 
> 1 error detected in the compilation of "/home/johnyi/Documents/DAN-master/cpp/Deform/build/deform_psroi_pooling_op_gpu.cpp1.ii".
> CMake Error at cuda_compile_2_generated_deform_psroi_pooling_op_gpu.cu.o.cmake:280 (message):
> Error generating file
> /home/johnyi/Documents/DAN-master/cpp/Deform/build/CMakeFiles/cuda_compile_2.dir//./cuda_compile_2_generated_deform_psroi_pooling_op_gpu.cu.o
> 
> CMakeFiles/deform.dir/build.make:70: recipe for target 'CMakeFiles/cuda_compile_2.dir/cuda_compile_2_generated_deform_psroi_pooling_op_gpu.cu.o' failed
> make[2]: *** [CMakeFiles/cuda_compile_2.dir/cuda_compile_2_generated_deform_psroi_pooling_op_gpu.cu.o] Error 1
> CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/deform.dir/all' failed

I have similar issue, is there a way to solve this
